# Development configuration
apiServer:
  port: 8080
  publicScheme: http
  publicHost: localhost
  publicPort: 8080

webServer:
  port: 8082
  publicScheme: http
  publicHost: localhost
  publicPort: 8082

insightsServer:
  port: 8081
  publicScheme: http
  publicHost: localhost
  publicPort: 8081

# This is the part I missed!
database:
  host: localhost
  port: 8093
  name: admin_butler
  user: postgres

# The fix for the upload error
maxRequestSize: 20971520
