# Project Configuration Passwords TEMPLATE
# Rename this file to passwords.yaml and add your keys

development:
  database: 'mysecretpassword'
  redis: ''
  serviceSecret: 'development-secret-123'
  geminiApiKey: 'INSERT_YOUR_KEY_HERE'

staging:
  database: 'mysecretpassword'
  redis: ''
  serviceSecret: 'staging-secret-123'
  geminiApiKey: 'INSERT_YOUR_KEY_HERE'

production:

  database: 'mysecretpassword'
  redis: ''
  serviceSecret: 'production-secret-123'
  geminiApiKey: 'INSERT_YOUR_KEY_HERE'
